<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VzQFTtRService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.vzQFTtR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'addressFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.address_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_AddressFormBuilderService', true],
            'addressFormHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.address_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_AddressFormHandlerService', true],
            'customerDataProvider' => ['services', 'prestashop.adapter.data_provider.customer', 'getPrestashop_Adapter_DataProvider_CustomerService', true],
        ], [
            'addressFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'addressFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
            'customerDataProvider' => 'PrestaShop\\PrestaShop\\Adapter\\Customer\\CustomerDataProvider',
        ]);

        if (isset($container->privates['.service_locator.vzQFTtR'])) {
            return $container->privates['.service_locator.vzQFTtR'];
        }

        return $container->privates['.service_locator.vzQFTtR'] = $instance;
    }
}
