<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8iCpQf7Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.8iCpQf7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.api_client_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_ApiClientFormBuilderService', true],
            'formHandler' => ['services', 'prestashop.core.form.identifiable_object.api_client_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_ApiClientFormHandlerService', true],
        ], [
            'formBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.8iCpQf7'])) {
            return $container->privates['.service_locator.8iCpQf7'];
        }

        return $container->privates['.service_locator.8iCpQf7'] = $instance;
    }
}
