<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZTOaeMRService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZTOaeMR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZTOaeMR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'featuresGridFactory' => ['services', 'prestashop.core.grid.grid_factory.feature', 'getPrestashop_Core_Grid_GridFactory_FeatureService', true],
            'filters' => ['privates', '.errored..service_locator.ZTOaeMR.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\FeatureFilters', NULL, 'Cannot autowire service ".service_locator.ZTOaeMR": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\FeatureFilters" but no such service exists.'],
        ], [
            'featuresGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\FeatureFilters',
        ]);
    }
}
