<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ta556UUService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ta556UU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'preferencesFormHandler' => ['services', 'prestashop.adapter.preferences.form_handler', 'getPrestashop_Adapter_Preferences_FormHandlerService', true],
        ], [
            'preferencesFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.Ta556UU'])) {
            return $container->privates['.service_locator.Ta556UU'];
        }

        return $container->privates['.service_locator.Ta556UU'] = $instance;
    }
}
