<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_KGJRhjoService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.kGJRhjo' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.kGJRhjo'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.search.command_handler.index_search_handler'] ?? $container->load('getPrestashop_Adapter_Search_CommandHandler_IndexSearchHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
