<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZA2m1fService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator._ZA2m1f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'backupFormHandler' => ['services', 'prestashop.admin.backup.form_handler', 'getPrestashop_Admin_Backup_FormHandlerService', true],
            'backupsGridFactory' => ['services', 'prestashop.core.grid.factory.backup', 'getPrestashop_Core_Grid_Factory_BackupService', true],
            'filters' => ['privates', '.errored..service_locator._ZA2m1f.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\BackupFilters', NULL, 'Cannot autowire service ".service_locator._ZA2m1f": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\BackupFilters" but no such service exists.'],
        ], [
            'backupFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'backupsGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\BackupFilters',
        ]);

        if (isset($container->privates['.service_locator._ZA2m1f'])) {
            return $container->privates['.service_locator._ZA2m1f'];
        }

        return $container->privates['.service_locator._ZA2m1f'] = $instance;
    }
}
