<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VEtHt_SService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.vEtHt.S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vEtHt.S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'giftOptionsFormHandler' => ['services', 'prestashop.admin.order_preferences.gift_options.form_handler', 'getPrestashop_Admin_OrderPreferences_GiftOptions_FormHandlerService', true],
        ], [
            'giftOptionsFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
