<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JQtOcApService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.JQtOcAp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JQtOcAp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'invoicePdfGenerator' => ['services', 'prestashop.adapter.pdf.order_invoice_pdf_generator', 'getPrestashop_Adapter_Pdf_OrderInvoicePdfGeneratorService', true],
        ], [
            'invoicePdfGenerator' => 'PrestaShop\\PrestaShop\\Adapter\\PDF\\OrderInvoicePdfGenerator',
        ]);
    }
}
