<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sn6ay0tService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.Sn6ay0t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.cart_summary_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_CartSummaryFormHandlerService', true],
        ], [
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.Sn6ay0t'])) {
            return $container->privates['.service_locator.Sn6ay0t'];
        }

        return $container->privates['.service_locator.Sn6ay0t'] = $instance;
    }
}
