<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M05w3QxService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.M05w3Qx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'configFormHandler' => ['services', 'prestashop.admin.image_settings.form_handler', 'getPrestashop_Admin_ImageSettings_FormHandlerService', true],
            'filters' => ['privates', '.errored..service_locator.M05w3Qx.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ImageTypeFilters', NULL, 'Cannot autowire service ".service_locator.M05w3Qx": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ImageTypeFilters" but no such service exists.'],
            'imageTypeGridFactory' => ['services', 'prestashop.core.grid.factory.image_type', 'getPrestashop_Core_Grid_Factory_ImageTypeService', true],
        ], [
            'configFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ImageTypeFilters',
            'imageTypeGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);

        if (isset($container->privates['.service_locator.M05w3Qx'])) {
            return $container->privates['.service_locator.M05w3Qx'];
        }

        return $container->privates['.service_locator.M05w3Qx'] = $instance;
    }
}
