<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UX1haR0Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.UX1haR0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'routeFinder' => ['services', 'prestashop.adapter.translation_route_finder', 'getPrestashop_Adapter_TranslationRouteFinderService', true],
        ], [
            'routeFinder' => 'PrestaShop\\PrestaShop\\Adapter\\Translations\\TranslationRouteFinder',
        ]);

        if (isset($container->privates['.service_locator.UX1haR0'])) {
            return $container->privates['.service_locator.UX1haR0'];
        }

        return $container->privates['.service_locator.UX1haR0'] = $instance;
    }
}
