<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_MsdDIIService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.MsdDI_i' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.MsdDI_i'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Discount\QueryHandler\GetDiscountTypesHandler(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountTypeRepository'] ?? $container->load('getDiscountTypeRepositoryService'))))->handle(...), ['method' => 'handle']);
    }
}
