<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7neki4wService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.7neki4w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'installedRtlLanguageChecker' => ['services', '.container.private.prestashop.adapter.language.rtl.installed_language_checker', 'get_Container_Private_Prestashop_Adapter_Language_Rtl_InstalledLanguageCheckerService', true],
            'logosUploadFormHandler' => ['services', 'prestashop.admin.shop_logos_settings.form_handler', 'getPrestashop_Admin_ShopLogosSettings_FormHandlerService', true],
            'themeProvider' => ['services', '.container.private.prestashop.core.addon.theme.theme_provider', 'get_Container_Private_Prestashop_Core_Addon_Theme_ThemeProviderService', true],
        ], [
            'installedRtlLanguageChecker' => '?',
            'logosUploadFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'themeProvider' => '?',
        ]);

        if (isset($container->privates['.service_locator.7neki4w'])) {
            return $container->privates['.service_locator.7neki4w'];
        }

        return $container->privates['.service_locator.7neki4w'] = $instance;
    }
}
