<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sm645eBService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.Sm645eB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sm645eB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zoneFilters' => ['privates', '.errored..service_locator.Sm645eB.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ZoneFilters', NULL, 'Cannot autowire service ".service_locator.Sm645eB": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ZoneFilters" but no such service exists.'],
            'zoneGridFactory' => ['services', 'prestashop.core.grid.factory.zone', 'getPrestashop_Core_Grid_Factory_ZoneService', true],
        ], [
            'zoneFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ZoneFilters',
            'zoneGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
