<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4LJcsUeService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.4LJcsUe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4LJcsUe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'positionDefinition' => ['services', 'prestashop.core.grid.attribute.position_definition', 'getPrestashop_Core_Grid_Attribute_PositionDefinitionService', true],
        ], [
            'positionDefinition' => 'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionDefinition',
        ]);
    }
}
