<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_39SPhIService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.39SPhI_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.39SPhI_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hookProvider' => ['services', 'hook_provider', 'getHookProviderService', true],
            'legacyContextService' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext', 'getLegacyContextService', false],
            'moduleAdapter' => ['services', 'prestashop.adapter.legacy.module', 'getPrestashop_Adapter_Legacy_ModuleService', true],
        ], [
            'hookProvider' => '?',
            'legacyContextService' => 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext',
            'moduleAdapter' => 'PrestaShop\\PrestaShop\\Adapter\\Module\\Module',
        ]);
    }
}
