<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QZlvCEaService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.qZlvCEa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'generalFormHandler' => ['services', 'prestashop.admin.product_preferences.general.form_handler', 'getPrestashop_Admin_ProductPreferences_General_FormHandlerService', true],
            'pageFormHandler' => ['services', 'prestashop.admin.product_preferences.page.form_handler', 'getPrestashop_Admin_ProductPreferences_Page_FormHandlerService', true],
            'paginationFormHandler' => ['services', 'prestashop.admin.product_preferences.pagination.form_handler', 'getPrestashop_Admin_ProductPreferences_Pagination_FormHandlerService', true],
            'stockFormHandler' => ['services', 'prestashop.admin.product_preferences.stock.form_handler', 'getPrestashop_Admin_ProductPreferences_Stock_FormHandlerService', true],
        ], [
            'generalFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'pageFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'paginationFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'stockFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.qZlvCEa'])) {
            return $container->privates['.service_locator.qZlvCEa'];
        }

        return $container->privates['.service_locator.qZlvCEa'] = $instance;
    }
}
