<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Core_Form_ChoiceProvider_ProductImagesChoiceProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.prestashop.core.form.choice_provider.product_images_choice_provider' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\ProductImagesChoiceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'));

        if (isset($container->services['.container.private.prestashop.core.form.choice_provider.product_images_choice_provider'])) {
            return $container->services['.container.private.prestashop.core.form.choice_provider.product_images_choice_provider'];
        }

        $instance = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\ProductImagesChoiceProvider($a, ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->getInt("PS_SHOP_DEFAULT"), ($container->services['PrestaShop\\PrestaShop\\Core\\Multistore\\MultistoreContextCheckerInterface'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context())->getContextShopID());

        if (isset($container->services['.container.private.prestashop.core.form.choice_provider.product_images_choice_provider'])) {
            return $container->services['.container.private.prestashop.core.form.choice_provider.product_images_choice_provider'];
        }

        return $container->services['.container.private.prestashop.core.form.choice_provider.product_images_choice_provider'] = $instance;
    }
}
