<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K7IecpWService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.K7IecpW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K7IecpW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carrierGridFactory' => ['services', 'prestashop.core.grid.factory.carrier', 'getPrestashop_Core_Grid_Factory_CarrierService', true],
            'carrierModuleAdviceAlertChecker' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Carrier\\CarrierModuleAdviceAlertChecker', 'getCarrierModuleAdviceAlertCheckerService', true],
            'employeeContext' => ['privates', 'PrestaShop\\PrestaShop\\Core\\Context\\EmployeeContext', 'getEmployeeContextService', false],
            'filters' => ['privates', '.errored..service_locator.K7IecpW.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CarrierFilters', NULL, 'Cannot autowire service ".service_locator.K7IecpW": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CarrierFilters" but no such service exists.'],
        ], [
            'carrierGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'carrierModuleAdviceAlertChecker' => 'PrestaShop\\PrestaShop\\Adapter\\Carrier\\CarrierModuleAdviceAlertChecker',
            'employeeContext' => 'PrestaShop\\PrestaShop\\Core\\Context\\EmployeeContext',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CarrierFilters',
        ]);
    }
}
