<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1sIDl0JService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.1sIDl0J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1sIDl0J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'geolocationWhitelistFormHandler' => ['services', 'prestashop.admin.geolocation.whitelist.form_handler', 'getPrestashop_Admin_Geolocation_Whitelist_FormHandlerService', true],
        ], [
            'geolocationWhitelistFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
