<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tnm4x9rService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.tnm4x9r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tnm4x9r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerGridFactory' => ['services', 'prestashop.core.grid.factory.customer', 'getPrestashop_Core_Grid_Factory_CustomerService', true],
            'filters' => ['privates', '.errored..service_locator.tnm4x9r.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerFilters', NULL, 'Cannot autowire service ".service_locator.tnm4x9r": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerFilters" but no such service exists.'],
        ], [
            'customerGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerFilters',
        ]);
    }
}
