<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QFQJVYVService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.qFQJVYV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qFQJVYV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'legacyContext' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext', 'getLegacyContextService', false],
            'modulePsClassicEdition' => ['services', 'ps_classic_edition.module', 'getPsClassicEdition_ModuleService', true],
            'psAccountHelper' => ['services', 'PrestaShop\\Module\\PsClassicEdition\\Helper\\PsAccountHelper', 'getPsAccountHelperService', true],
        ], [
            'legacyContext' => 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext',
            'modulePsClassicEdition' => 'ps_classic_edition',
            'psAccountHelper' => 'PrestaShop\\Module\\PsClassicEdition\\Helper\\PsAccountHelper',
        ]);
    }
}
