<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WVBQyService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.w_VB_qy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currencyFormBuilder' => ['services', 'prestashop.core.form.builder.currency_form_builder', 'getPrestashop_Core_Form_Builder_CurrencyFormBuilderService', true],
            'currencyFormHandler' => ['services', 'prestashop.core.form.identifiable_object.currency_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_CurrencyFormHandlerService', true],
        ], [
            'currencyFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'currencyFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.w_VB_qy'])) {
            return $container->privates['.service_locator.w_VB_qy'];
        }

        return $container->privates['.service_locator.w_VB_qy'] = $instance;
    }
}
