<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RqINX1LService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.RqINX1L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RqINX1L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currencyDataProvider' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider', 'getCurrencyDataProviderService', false],
            'featureFlagStateChecker' => ['services', 'PrestaShop\\PrestaShop\\Core\\FeatureFlag\\FeatureFlagStateCheckerInterface', 'getFeatureFlagStateCheckerInterfaceService', false],
            'formBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.cancel_product_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_CancelProductFormBuilderService', true],
        ], [
            'currencyDataProvider' => 'PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider',
            'featureFlagStateChecker' => '?',
            'formBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
        ]);
    }
}
