<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NfbM6zKService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.NfbM6zK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formHandler' => ['services', 'prestashop.adapter.order.delivery.slip.options.form_handler', 'getPrestashop_Adapter_Order_Delivery_Slip_Options_FormHandlerService', true],
            'pdfFormHandler' => ['services', 'prestashop.adapter.order.delivery.slip.pdf.form_handler', 'getPrestashop_Adapter_Order_Delivery_Slip_Pdf_FormHandlerService', true],
        ], [
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'pdfFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.NfbM6zK'])) {
            return $container->privates['.service_locator.NfbM6zK'];
        }

        return $container->privates['.service_locator.NfbM6zK'] = $instance;
    }
}
