<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SIJ_LShService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.sIJ.lSh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sIJ.lSh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'generalFormHandler' => ['services', 'prestashop.admin.order_preferences.general.form_handler', 'getPrestashop_Admin_OrderPreferences_General_FormHandlerService', true],
        ], [
            'generalFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
