<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6Kxy47dService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.6Kxy47d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Kxy47d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.6Kxy47d.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductFilters', NULL, 'Cannot autowire service ".service_locator.6Kxy47d": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductFilters" but no such service exists.'],
            'gridFactory' => ['services', 'prestashop.core.grid.factory.product_light', 'getPrestashop_Core_Grid_Factory_ProductLightService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductFilters',
            'gridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
