<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S_DEetService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.S.D_Eet' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currencyGridFactory' => ['services', 'prestashop.core.grid.factory.currency', 'getPrestashop_Core_Grid_Factory_CurrencyService', true],
            'filters' => ['privates', '.errored..service_locator.S.D_Eet.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CurrencyFilters', NULL, 'Cannot autowire service ".service_locator.S.D_Eet": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CurrencyFilters" but no such service exists.'],
            'settingsFormHandler' => ['services', 'prestashop.admin.currency_settings.form_handler', 'getPrestashop_Admin_CurrencySettings_FormHandlerService', true],
        ], [
            'currencyGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CurrencyFilters',
            'settingsFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.S.D_Eet'])) {
            return $container->privates['.service_locator.S.D_Eet'];
        }

        return $container->privates['.service_locator.S.D_Eet'] = $instance;
    }
}
