<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X0GVDjZService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.X0GVDjZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X0GVDjZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currencyDataProvider' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider', 'getCurrencyDataProviderService', false],
            'featureFlagStateChecker' => ['services', 'PrestaShop\\PrestaShop\\Core\\FeatureFlag\\FeatureFlagStateCheckerInterface', 'getFeatureFlagStateCheckerInterfaceService', false],
            'filters' => ['privates', '.errored..service_locator.X0GVDjZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ShipmentFilters', NULL, 'Cannot autowire service ".service_locator.X0GVDjZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ShipmentFilters" but no such service exists.'],
            'formBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.cancel_product_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_CancelProductFormBuilderService', true],
            'orderSiblingProvider' => ['services', 'prestashop.adapter.order.order_sibling_provider', 'getPrestashop_Adapter_Order_OrderSiblingProviderService', true],
            'shipmentGridFactory' => ['services', 'PrestaShop\\PrestaShop\\Core\\Grid\\Factory\\ShipmentFactory', 'getShipmentFactoryService', true],
            'tools' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Tools', 'getToolsService', false],
        ], [
            'currencyDataProvider' => 'PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider',
            'featureFlagStateChecker' => '?',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ShipmentFilters',
            'formBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'orderSiblingProvider' => 'PrestaShop\\PrestaShop\\Core\\Order\\OrderSiblingProviderInterface',
            'shipmentGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'tools' => 'PrestaShop\\PrestaShop\\Adapter\\Tools',
        ]);
    }
}
