<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JUHcvu9Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.jUHcvu9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paymentModulesListProvider' => ['services', 'prestashop.adapter.module.payment_module_provider', 'getPrestashop_Adapter_Module_PaymentModuleProviderService', true],
            'paymentPreferencesFormHandler' => ['services', 'prestashop.admin.payment_preferences.form_handler', 'getPrestashop_Admin_PaymentPreferences_FormHandlerService', true],
        ], [
            'paymentModulesListProvider' => 'PrestaShop\\PrestaShop\\Core\\Module\\DataProvider\\PaymentModuleListProviderInterface',
            'paymentPreferencesFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.jUHcvu9'])) {
            return $container->privates['.service_locator.jUHcvu9'];
        }

        return $container->privates['.service_locator.jUHcvu9'] = $instance;
    }
}
