<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EP6eWndService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.eP6eWnd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eP6eWnd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attributeFilters' => ['privates', '.errored..service_locator.eP6eWnd.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeFilters', NULL, 'Cannot autowire service ".service_locator.eP6eWnd": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeFilters" but no such service exists.'],
            'attributeGridFactory' => ['services', 'prestashop.core.grid.factory.attribute', 'getPrestashop_Core_Grid_Factory_AttributeService', true],
            'attributeGroupViewDataProvider' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\AttributeGroup\\AttributeGroupViewDataProvider', 'getAttributeGroupViewDataProviderService', true],
        ], [
            'attributeFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeFilters',
            'attributeGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'attributeGroupViewDataProvider' => 'PrestaShop\\PrestaShop\\Adapter\\AttributeGroup\\AttributeGroupViewDataProvider',
        ]);
    }
}
