<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HnE0BNsService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.hnE0BNs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hnE0BNs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'memcacheServerManager' => ['services', 'prestashop.adapter.memcache_server.manager', 'getPrestashop_Adapter_MemcacheServer_ManagerService', true],
        ], [
            'memcacheServerManager' => 'PrestaShop\\PrestaShop\\Adapter\\Cache\\MemcacheServerManager',
        ]);
    }
}
