<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7WSL7Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.7_w_SL7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'advancedFormHandler' => ['services', 'prestashop.admin.localization.advanced.form_handler', 'getPrestashop_Admin_Localization_Advanced_FormHandlerService', true],
            'configurationFormHandler' => ['services', 'prestashop.admin.localization.configuration.form_handler', 'getPrestashop_Admin_Localization_Configuration_FormHandlerService', true],
            'localUnitsFormHandler' => ['services', 'prestashop.admin.localization.local_units.form_handler', 'getPrestashop_Admin_Localization_LocalUnits_FormHandlerService', true],
        ], [
            'advancedFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'configurationFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'localUnitsFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.7_w_SL7'])) {
            return $container->privates['.service_locator.7_w_SL7'];
        }

        return $container->privates['.service_locator.7_w_SL7'] = $instance;
    }
}
