<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fpx7NY1Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.fpx7NY1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fpx7NY1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'addressesGridFactory' => ['services', 'prestashop.core.grid.grid_factory.manufacturer_address', 'getPrestashop_Core_Grid_GridFactory_ManufacturerAddressService', true],
            'filters' => ['privates', '.errored..service_locator.fpx7NY1.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerAddressFilters', NULL, 'Cannot autowire service ".service_locator.fpx7NY1": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerAddressFilters" but no such service exists.'],
        ], [
            'addressesGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerAddressFilters',
        ]);
    }
}
