<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QWPSL6Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.q_WPSL6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q_WPSL6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cachingFormHandler' => ['services', 'prestashop.adapter.performance.caching.form_handler', 'getPrestashop_Adapter_Performance_Caching_FormHandlerService', true],
        ], [
            'cachingFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
