<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutCommandService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Command\AboutCommand' shared service.
     *
     * @return \PrestaShopBundle\Command\AboutCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Command\\AboutCommand'] = $instance = new \PrestaShopBundle\Command\AboutCommand(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));

        $instance->setName('about');
        $instance->setDescription('Display information about the current project');

        return $instance;
    }
}
