<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutCommand_LazyService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.PrestaShopBundle\Command\AboutCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.PrestaShopBundle\\Command\\AboutCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('about', [], 'Display information about the current project', false, #[\Closure(name: 'PrestaShopBundle\\Command\\AboutCommand')] fn (): \PrestaShopBundle\Command\AboutCommand => ($container->services['PrestaShopBundle\\Command\\AboutCommand'] ?? $container->load('getAboutCommandService')));
    }
}
