<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Infrastructure\Repository\ConfigurationRepository' shared service.
     *
     * @return \PsCheckout\Infrastructure\Repository\ConfigurationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Infrastructure\\Repository\\ConfigurationRepository'] = new \PsCheckout\Infrastructure\Repository\ConfigurationRepository(($container->services['ps_checkout.db'] ?? $container->load('getPsCheckout_DbService')), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)));
    }
}
