<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContextModuleService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ContextModule' shared service.
     *
     * @return \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ContextModule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\ContextModule'] = new \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ContextModule(($container->services['ps_checkout.module'] ?? $container->load('getPsCheckout_ModuleService'))->name, ($container->services['ps_checkout.module'] ?? $container->load('getPsCheckout_ModuleService'))->version, ($container->services['PsCheckout\\Infrastructure\\Adapter\\Context'] ??= new \PsCheckout\Infrastructure\Adapter\Context()), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Link'] ?? $container->load('getLinkService')), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)), ($container->services['PsCheckout\\Infrastructure\\Environment\\Env'] ?? $container->load('getEnv4Service')));
    }
}
