<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationModuleService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ConfigurationModule' shared service.
     *
     * @return \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ConfigurationModule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\ConfigurationModule'] = new \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ConfigurationModule(($container->services['ps_checkout.module'] ?? $container->load('getPsCheckout_ModuleService'))->id, ($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)), ($container->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourcePresenter'] ?? $container->load('getFundingSourcePresenterService')), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Context'] ??= new \PsCheckout\Infrastructure\Adapter\Context())->getShop()->id);
    }
}
