<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartFilterService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.AM62hHI.PrestaShop\PrestaShop\Core\Search\Filters\CartFilter' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\CartFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AM62hHI": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CartFilter" but no such service exists.');
    }
}
