<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompatibilityRulesInstallerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Infrastructure\Bootstrap\Install\CompatibilityRulesInstaller' shared service.
     *
     * @return \PsCheckout\Infrastructure\Bootstrap\Install\CompatibilityRulesInstaller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\CompatibilityRulesInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\CompatibilityRulesInstaller(($container->services['PsCheckout\\Infrastructure\\Repository\\CountryRepository'] ?? $container->load('getCountryRepository3Service')), ($container->services['PsCheckout\\Infrastructure\\Repository\\CurrencyRepository'] ?? $container->load('getCurrencyRepository3Service')));
    }
}
