<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangeStatesZoneTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Improve\International\Locations\ChangeStatesZoneType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\International\Locations\ChangeStatesZoneType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Improve\\International\\Locations\\ChangeStatesZoneType'] = new \PrestaShopBundle\Form\Admin\Improve\International\Locations\ChangeStatesZoneType(($container->services['.container.private.prestashop.core.form.choice_provider.zone_by_id'] ??= new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ZoneByIdChoiceProvider()));
    }
}
