<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountRepository' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Validate\\DiscountValidator'] ?? $container->load('getDiscountValidatorService'));

        if (isset($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'])) {
            return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'];
        }

        $instance = new \PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountRepository($a, ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), 'vovsk_');

        if (isset($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'])) {
            return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'];
        }

        return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'] = $instance;
    }
}
