<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountValidatorService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator(($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepository3Service')), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Combination\\Repository\\CombinationRepository'] ?? $container->load('getCombinationRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Carrier\\Repository\\CarrierRepository'] ?? $container->load('getCarrierRepository3Service')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Manufacturer\\Repository\\ManufacturerRepository'] ??= new \PrestaShop\PrestaShop\Adapter\Manufacturer\Repository\ManufacturerRepository()), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Attribute\\Repository\\AttributeRepository'] ?? $container->load('getAttributeRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Supplier\\Repository\\SupplierRepository'] ??= new \PrestaShop\PrestaShop\Adapter\Supplier\Repository\SupplierRepository()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Category\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepository2Service')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Country\\Repository\\CountryRepository'] ?? self::getCountryRepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Customer\\Group\\Repository\\GroupRepository'] ??= new \PrestaShop\PrestaShop\Adapter\Customer\Group\Repository\GroupRepository()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\Repository\\FeatureValueRepository'] ?? $container->load('getFeatureValueRepositoryService')));

        if (isset($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Validate\\DiscountValidator'])) {
            return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Validate\\DiscountValidator'];
        }

        $container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Validate\\DiscountValidator'] = $instance;

        $instance->setDiscountRepository(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'] ?? $container->load('getDiscountRepositoryService')));

        return $instance;
    }
}
