<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExternalShipmentProcessorService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\PayPal\ShippingTracking\Processor\ExternalShipmentProcessor' shared service.
     *
     * @return \PsCheckout\Core\PayPal\ShippingTracking\Processor\ExternalShipmentProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Processor\\ExternalShipmentProcessor'] = new \PsCheckout\Core\PayPal\ShippingTracking\Processor\ExternalShipmentProcessor(($container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Validator\\OrderTrackerValidator'] ?? $container->load('getOrderTrackerValidatorService')), ($container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Builder\\TrackingPayloadBuilder'] ?? $container->load('getTrackingPayloadBuilderService')), ($container->services['PsCheckout\\Infrastructure\\Repository\\ShippingTrackingRepository'] ?? $container->load('getShippingTrackingRepositoryService')), ($container->services['Psr\\Log\\LoggerInterface'] ?? self::getLoggerInterfaceService($container)), ($container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Cache\\ShippingTrackingCache'] ?? $container->load('getShippingTrackingCacheService')), ($container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Service\\TrackingApiService'] ?? $container->load('getTrackingApiServiceService')), ($container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Service\\TrackingDatabaseHandler'] ?? $container->load('getTrackingDatabaseHandlerService')), ($container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Action\\AddTrackingActionInterface'] ?? $container->load('getAddTrackingActionInterfaceService')));
    }
}
