<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterLinkFilterTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Type\FilterLinkFilterType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Type\FilterLinkFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Type\\FilterLinkFilterType'] = new \PrestaShopBundle\Form\Admin\Type\FilterLinkFilterType();
    }
}
