<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFundingSourceInstallerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Infrastructure\Bootstrap\Install\FundingSourceInstaller' shared service.
     *
     * @return \PsCheckout\Infrastructure\Bootstrap\Install\FundingSourceInstaller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\FundingSourceInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\FundingSourceInstaller(($container->services['PsCheckout\\Infrastructure\\Repository\\ShopRepository'] ??= new \PsCheckout\Infrastructure\Repository\ShopRepository()), ($container->services['PsCheckout\\Infrastructure\\Repository\\FundingSourceRepository'] ?? $container->load('getFundingSourceRepositoryService')));
    }
}
