<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilesystemAdapterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'Symfony\Component\Cache\Adapter\FilesystemAdapter' shared autowired service.
     *
     * @return \Symfony\Component\Cache\Adapter\FilesystemAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Symfony\\Component\\Cache\\Adapter\\FilesystemAdapter'] = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('', 0, (\dirname(__DIR__, 5).'/var/cache/prod'.\DIRECTORY_SEPARATOR.'%/ps_mbo'));
    }
}
