<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeatureControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\FeatureController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController(($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\FeatureFeature'] ?? $container->load('getFeatureFeatureService')));

        $instance->setContainer(($container->privates['.service_locator.7qVRPWR'] ?? $container->load('get_ServiceLocator_7qVRPWRService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\FeatureController', $container));

        return $instance;
    }
}
