<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGridPresenterInterfaceService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Core\Grid\Presenter\GridPresenterInterface' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Presenter\GridPresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Presenter\\GridPresenterInterface'] = new \PrestaShop\PrestaShop\Core\Grid\Presenter\GridPresenter(($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)));
    }
}
