<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookActionObjectCarrierUpdateAfterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\Psshipping\Hooks\HookActionObjectCarrierUpdateAfter' shared service.
     *
     * @return \PrestaShop\Module\Psshipping\Hooks\HookActionObjectCarrierUpdateAfter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Psshipping\\Hooks\\HookActionObjectCarrierUpdateAfter'] = new \PrestaShop\Module\Psshipping\Hooks\HookActionObjectCarrierUpdateAfter(($container->services['psshipping'] ?? $container->load('getPsshippingService')), ($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\CarrierRepository'] ?? $container->load('getCarrierRepositoryService')), ($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Orders\\OrdersRepository'] ?? $container->load('getOrdersRepositoryService')));
    }
}
