<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookActionValidateOrderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\Psshipping\Hooks\HookActionValidateOrder' shared service.
     *
     * @return \PrestaShop\Module\Psshipping\Hooks\HookActionValidateOrder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Psshipping\\Hooks\\HookActionValidateOrder'] = new \PrestaShop\Module\Psshipping\Hooks\HookActionValidateOrder(($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\CarrierRepository'] ?? $container->load('getCarrierRepositoryService')), ($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\PickupPoints\\PsshippingAddressRepository'] ?? $container->load('getPsshippingAddressRepositoryService')), ($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\PickupPoints\\PsshippingAddressOrdersRepository'] ?? $container->load('getPsshippingAddressOrdersRepositoryService')), ($container->services['psshipping.context'] ?? $container->load('getPsshipping_ContextService')));
    }
}
