<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogsControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\LogsController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\LogsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\LogsController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\LogsController();

        $instance->setContainer(($container->privates['.service_locator.7qVRPWR'] ?? $container->load('get_ServiceLocator_7qVRPWRService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\LogsController', $container));

        return $instance;
    }
}
