<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkBlockRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\LinkList\Repository\LinkBlockRepository' shared service.
     *
     * @return \PrestaShop\Module\LinkList\Repository\LinkBlockRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\LinkList\\Repository\\LinkBlockRepository'] = new \PrestaShop\Module\LinkList\Repository\LinkBlockRepository(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), 'vovsk_', ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(false, ($container->services['PrestaShop\\PrestaShop\\Core\\Multistore\\MultistoreContextCheckerInterface'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context())->getContextShopID()), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature'] ?? self::getMultistoreFeatureService($container))->isUsed(), ($container->services['PrestaShop\\PrestaShop\\Core\\Multistore\\MultistoreContextCheckerInterface'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context()), ($container->services['prestashop.module.link_block.adapter.object_model_handler'] ??= new \PrestaShop\Module\LinkList\Adapter\ObjectModelHandler()));
    }
}
