<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderStateTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderStates\OrderStateType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderStates\OrderStateType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\OrderStates\\OrderStateType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\OrderStates\\OrderStateType'];
        }

        $instance = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderStates\OrderStateType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(false), ($container->services['PrestaShop\\PrestaShop\\Core\\MailTemplate\\FolderThemeCatalog'] ?? $container->load('getFolderThemeCatalogService')), $a, ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['prestashop.core.email.legacy_template_lister'] ??= new \PrestaShop\PrestaShop\Core\Email\LegacyEmailTemplateLister((\dirname(__DIR__, 5).'/mails'), (\dirname(__DIR__, 5).'/modules'))));

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\OrderStates\\OrderStateType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\OrderStates\\OrderStateType'];
        }

        return $container->privates['PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\OrderStates\\OrderStateType'] = $instance;
    }
}
