<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderPayloadBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\Order\Builder\OrderPayloadBuilder' shared service.
     *
     * @return \PsCheckout\Core\Order\Builder\OrderPayloadBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\Order\\Builder\\OrderPayloadBuilder'] = new \PsCheckout\Core\Order\Builder\OrderPayloadBuilder(($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\BaseNodeBuilder'] ?? $container->load('getBaseNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\AmountBreakdownNode'] ??= new \PsCheckout\Core\Order\Builder\Node\AmountBreakdownNode()), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\ShippingNodeBuilder'] ?? $container->load('getShippingNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\PayerNodeBuilder'] ?? $container->load('getPayerNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\CardPaymentSourceNodeBuilder'] ?? $container->load('getCardPaymentSourceNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\SupplementaryDataNodeBuilder'] ?? $container->load('getSupplementaryDataNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\ApplicationContextNodeBuilder'] ?? $container->load('getApplicationContextNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\PayPalPaymentSourceNodeBuilder'] ?? $container->load('getPayPalPaymentSourceNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\GooglePayPaymentSourceNodeBuilder'] ?? $container->load('getGooglePayPaymentSourceNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\PaymentSource\\VenmoPaymentSourceNodeBuilder'] ?? $container->load('getVenmoPaymentSourceNodeBuilderService')), ($container->services['PsCheckout\\Core\\Order\\Builder\\Node\\PuiPaymentSourceNodeBuilder'] ?? $container->load('getPuiPaymentSourceNodeBuilderService')));
    }
}
