<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderDetailRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Adapter\Order\Repository\OrderDetailRepository' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Order\Repository\OrderDetailRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Order\\Repository\\OrderDetailRepository'] = new \PrestaShop\PrestaShop\Adapter\Order\Repository\OrderDetailRepository();
    }
}
