<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessorService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'ApiPlatform\Symfony\Messenger\Processor' shared service.
     *
     * @return \ApiPlatform\Symfony\Messenger\Processor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['ApiPlatform\\Symfony\\Messenger\\Processor'])) {
            return $container->privates['ApiPlatform\\Symfony\\Messenger\\Processor'];
        }

        $instance = new \ApiPlatform\Symfony\Messenger\Processor($a);

        if (isset($container->privates['ApiPlatform\\Symfony\\Messenger\\Processor'])) {
            return $container->privates['ApiPlatform\\Symfony\\Messenger\\Processor'];
        }

        return $container->privates['ApiPlatform\\Symfony\\Messenger\\Processor'] = $instance;
    }
}
