<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalOrderCacheService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\PayPal\Order\Cache\PayPalOrderCache' shared service.
     *
     * @return \PsCheckout\Core\PayPal\Order\Cache\PayPalOrderCache
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\PayPal\\Order\\Cache\\PayPalOrderCache'] = new \PsCheckout\Core\PayPal\Order\Cache\PayPalOrderCache(($container->services['PsCheckout\\Cache\\Array\\PayPalOrder'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()), ($container->services['PsCheckout\\Cache\\FileSystem\\PayPalOrder'] ?? $container->load('getPayPalOrder2Service')), ($container->services['PsCheckout\\Core\\PayPal\\OrderStatus\\Action\\PayPalCheckOrderStatusAction'] ??= new \PsCheckout\Core\PayPal\OrderStatus\Action\PayPalCheckOrderStatusAction()));
    }
}
