<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Form_IdentifiableObject_CombinationListFormHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.form.identifiable_object.combination_list_form_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'));

        if (isset($container->services['prestashop.core.form.identifiable_object.combination_list_form_handler'])) {
            return $container->services['prestashop.core.form.identifiable_object.combination_list_form_handler'];
        }

        $instance = ($container->services['prestashop.core.form.identifiable_object.handler.form_handler_factory'] ?? $container->load('getPrestashop_Core_Form_IdentifiableObject_Handler_FormHandlerFactoryService'))->create(new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataHandler\CombinationListFormDataHandler($a, new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataFormatter\CombinationListFormDataFormatter('modify_all_shops_'), ($container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\CommandBuilder\\Product\\Combination\\CombinationCommandsBuilder'] ?? $container->load('getCombinationCommandsBuilderService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Multistore\\MultistoreContextCheckerInterface'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context())->getContextShopID(), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->getInt("PS_SHOP_DEFAULT")));

        if (isset($container->services['prestashop.core.form.identifiable_object.combination_list_form_handler'])) {
            return $container->services['prestashop.core.form.identifiable_object.combination_list_form_handler'];
        }

        return $container->services['prestashop.core.form.identifiable_object.combination_list_form_handler'] = $instance;
    }
}
