<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalOrderPresenterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderPresenter' shared service.
     *
     * @return \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderPresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Presentation\\Presenter\\PayPalOrder\\PayPalOrderPresenter'] = new \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderPresenter(($container->services['PsCheckout\\Presentation\\Presenter\\PayPalOrder\\PayPalOrderTransactionPresenter'] ?? $container->load('getPayPalOrderTransactionPresenterService')), ($container->services['PsCheckout\\Presentation\\Presenter\\PayPalOrder\\PayPalOrderTotalsPresenter'] ??= new \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTotalsPresenter()), ($container->services['PsCheckout\\Core\\PayPal\\Card3DSecure\\Card3DSecureValidator'] ??= new \PsCheckout\Core\PayPal\Card3DSecure\Card3DSecureValidator()), ($container->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\LogoPresenter'] ?? $container->load('getLogoPresenterService')), ($container->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourceTranslationProvider'] ?? $container->load('getFundingSourceTranslationProviderService')), ($container->services['PsCheckout\\Module\\Presentation\\Translator'] ?? $container->load('getTranslatorService')), ($container->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRepository'] ?? $container->load('getPayPalOrderRepositoryService')));
    }
}
