<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductFilters3Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.tuFAzQ5.PrestaShop\PrestaShop\Core\Search\Filters\ProductFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\ProductFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tuFAzQ5": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductFilters" but no such service exists.');
    }
}
