<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalOrderTotalsPresenterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTotalsPresenter' shared service.
     *
     * @return \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTotalsPresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Presentation\\Presenter\\PayPalOrder\\PayPalOrderTotalsPresenter'] = new \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTotalsPresenter();
    }
}
