<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Search_CommandHandler_IndexSearchHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.search.command_handler.index_search_handler' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Search\CommandHandler\SearchIndexationHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.search.command_handler.index_search_handler'] = new \PrestaShop\PrestaShop\Adapter\Search\CommandHandler\SearchIndexationHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepository3Service')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Shop\\Repository\\ShopRepository'] ?? self::getShopRepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Shop\\Repository\\ShopGroupRepository'] ?? $container->load('getShopGroupRepositoryService')));
    }
}
