<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Webservice_CommandHandler_DeleteWebserviceKeyHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.webservice.command_handler.delete_webservice_key_handler' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Webservice\CommandHandler\DeleteWebserviceKeyHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.webservice.command_handler.delete_webservice_key_handler'] = new \PrestaShop\PrestaShop\Adapter\Webservice\CommandHandler\DeleteWebserviceKeyHandler(($container->services['.container.private.prestashop.adapter.webservice.webservice_key_eraser'] ??= new \PrestaShop\PrestaShop\Adapter\Webservice\WebserviceKeyEraser()));
    }
}
