<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Api_FeatureAttribute_RepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.api.feature_attribute.repository' shared autowired service.
     *
     * @return \PrestaShopBundle\Entity\Repository\FeatureAttributeRepository
     *
     * @deprecated Since PrestaShop\PrestaShop 9.1: The "prestashop.core.api.feature_attribute.repository" service is deprecated. You should stop using it, as it will be removed in the future.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('PrestaShop\\PrestaShop', '9.1', 'The "prestashop.core.api.feature_attribute.repository" service is deprecated. You should stop using it, as it will be removed in the future.');

        return $container->services['prestashop.core.api.feature_attribute.repository'] = new \PrestaShopBundle\Entity\Repository\FeatureAttributeRepository(($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Feature\\Repository\\FeatureRepository'] ?? $container->load('getFeatureRepositoryService')), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Attribute\\Repository\\AttributeRepository'] ?? $container->load('getAttributeRepositoryService')));
    }
}
