<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalOrderTransactionPresenterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTransactionPresenter' shared service.
     *
     * @return \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTransactionPresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Presentation\\Presenter\\PayPalOrder\\PayPalOrderTransactionPresenter'] = new \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTransactionPresenter(($container->services['PsCheckout\\Presentation\\Presenter\\Date\\DatePresenter'] ?? $container->load('getDatePresenterService')), ($container->services['PsCheckout\\Module\\Presentation\\Translator'] ?? $container->load('getTranslatorService')));
    }
}
