<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Form_IdentifiableObject_DataProvider_CatalogPriceRuleFormDataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.form.identifiable_object.data_provider.catalog_price_rule_form_data_provider' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CatalogPriceRuleFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'));

        if (isset($container->services['prestashop.core.form.identifiable_object.data_provider.catalog_price_rule_form_data_provider'])) {
            return $container->services['prestashop.core.form.identifiable_object.data_provider.catalog_price_rule_form_data_provider'];
        }

        $instance = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CatalogPriceRuleFormDataProvider($a);

        if (isset($container->services['prestashop.core.form.identifiable_object.data_provider.catalog_price_rule_form_data_provider'])) {
            return $container->services['prestashop.core.form.identifiable_object.data_provider.catalog_price_rule_form_data_provider'];
        }

        return $container->services['prestashop.core.form.identifiable_object.data_provider.catalog_price_rule_form_data_provider'] = $instance;
    }
}
