<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_EmployeeLanguageUpdaterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.employee_language_updater' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Employee\EmployeeLanguageUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.employee_language_updater'] = new \PrestaShop\PrestaShop\Adapter\Employee\EmployeeLanguageUpdater(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), 'vovsk_', ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->get("PS_LANG_DEFAULT"));
    }
}
