<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Security_Voter_ProductService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'prestashop.security.voter.product' shared autowired service.
     *
     * @return \PrestaShopBundle\Security\Voter\PageVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['prestashop.security.voter.product'] = new \PrestaShopBundle\Security\Voter\PageVoter(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Security\\Access'] ??= new \PrestaShop\PrestaShop\Adapter\Security\Access()));
    }
}
