<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryListProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\ApiPlatform\Provider\QueryListProvider' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\Provider\QueryListProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['PrestaShopBundle\\ApiPlatform\\Serializer\\CQRSApiSerializer'] ?? self::getCQRSApiSerializerService($container));

        if (isset($container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'])) {
            return $container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'];
        }
        $b = ($container->services['prestashop.core.api.search.builder'] ?? $container->load('getPrestashop_Core_Api_Search_BuilderService'));

        if (isset($container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'])) {
            return $container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'];
        }
        $c = ($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'));

        if (isset($container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'])) {
            return $container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'];
        }

        $instance = new \PrestaShopBundle\ApiPlatform\Provider\QueryListProvider(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, $container, ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)), $b, $c, ($container->privates['PrestaShopBundle\\ApiPlatform\\ContextParametersProvider'] ?? self::getContextParametersProviderService($container)), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)));

        if (isset($container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'])) {
            return $container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'];
        }

        return $container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'] = $instance;
    }
}
