<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegenerateThumbnailsCommand_LazyService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.PrestaShopBundle\Command\RegenerateThumbnailsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.PrestaShopBundle\\Command\\RegenerateThumbnailsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('prestashop:thumbnails:regenerate', [], 'Regenerate thumbnails', false, #[\Closure(name: 'PrestaShopBundle\\Command\\RegenerateThumbnailsCommand')] fn (): \PrestaShopBundle\Command\RegenerateThumbnailsCommand => ($container->services['PrestaShopBundle\\Command\\RegenerateThumbnailsCommand'] ?? $container->load('getRegenerateThumbnailsCommandService')));
    }
}
