<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegenerateThumbnailsCommandService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Command\RegenerateThumbnailsCommand' shared service.
     *
     * @return \PrestaShopBundle\Command\RegenerateThumbnailsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Command\\RegenerateThumbnailsCommand'] = $instance = new \PrestaShopBundle\Command\RegenerateThumbnailsCommand(($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService')));

        $instance->setName('prestashop:thumbnails:regenerate');
        $instance->setDescription('Regenerate thumbnails');

        return $instance;
    }
}
