<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipmentGridDefinitionFactoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ShipmentGridDefinitionFactory' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ShipmentGridDefinitionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Definition\\Factory\\ShipmentGridDefinitionFactory'] = $instance = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ShipmentGridDefinitionFactory(($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)));

        $instance->setTranslator(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)));

        return $instance;
    }
}
