<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStateFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.9JEoFZ..PrestaShop\PrestaShop\Core\Search\Filters\StateFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\StateFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9JEoFZ.": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StateFilters" but no such service exists.');
    }
}
