<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetRefundedOrderStateActionService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\OrderState\Action\SetRefundedOrderStateAction' shared service.
     *
     * @return \PsCheckout\Core\OrderState\Action\SetRefundedOrderStateAction
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\OrderState\\Action\\SetRefundedOrderStateAction'] = new \PsCheckout\Core\OrderState\Action\SetRefundedOrderStateAction(($container->services['PsCheckout\\Core\\PayPal\\Refund\\Provider\\PayPalRefundOrderProvider'] ?? $container->load('getPayPalRefundOrderProviderService')), ($container->services['PsCheckout\\Core\\PayPal\\Order\\Provider\\PayPalOrderProvider'] ?? $container->load('getPayPalOrderProviderService')), ($container->services['PsCheckout\\Core\\OrderState\\Service\\OrderStateMapper'] ?? $container->load('getOrderStateMapperService')), ($container->services['PsCheckout\\Core\\OrderState\\Action\\ChangeOrderStateAction'] ?? $container->load('getChangeOrderStateActionService')), ($container->services['PsCheckout\\Core\\PayPal\\Order\\Cache\\PayPalOrderCache'] ?? $container->load('getPayPalOrderCacheService')));
    }
}
