<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchemaSynchronizerService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\ApiPlatform\OpenApi\Adapter\SchemaSynchronizer' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\OpenApi\Adapter\SchemaSynchronizer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\ApiPlatform\\OpenApi\\Adapter\\SchemaSynchronizer'] = new \PrestaShopBundle\ApiPlatform\OpenApi\Adapter\SchemaSynchronizer(($container->privates['property_info.cache'] ?? self::getPropertyInfo_CacheService($container)), ($container->privates['api_platform.serializer.mapping.cache_class_metadata_factory'] ?? self::getApiPlatform_Serializer_Mapping_CacheClassMetadataFactoryService($container)), ($container->privates['PrestaShopBundle\\ApiPlatform\\DomainObjectDetector'] ?? self::getDomainObjectDetectorService($container)));
    }
}
