<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipmentGridDataFactoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\ShipmentGridDataFactory' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Data\Factory\ShipmentGridDataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Data\\Factory\\ShipmentGridDataFactory'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\ShipmentGridDataFactory(($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Data\\Factory\\Shipment'] ?? $container->load('getShipmentService')), ($container->services['prestashop.core.localization.locale.context_locale'] ?? $container->load('getPrestashop_Core_Localization_Locale_ContextLocaleService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CurrencyContext'] ?? self::getCurrencyContextService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
