<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonyCacheClearerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Cache\\Clearer\\SymfonyCacheClearer'] = new \PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['PrestaShop\\PrestaShop\\Adapter\\Cache\\Clearer\\Symfony\\ExecKernelCacheClearer'] ?? $container->load('getExecKernelCacheClearerService'));
            yield 1 => ($container->services['PrestaShop\\PrestaShop\\Adapter\\Cache\\Clearer\\Symfony\\ApplicationKernelCacheClearer'] ?? $container->load('getApplicationKernelCacheClearerService'));
            yield 2 => ($container->services['PrestaShop\\PrestaShop\\Adapter\\Cache\\Clearer\\Symfony\\FilesystemKernelCacheClearer'] ?? $container->load('getFilesystemKernelCacheClearerService'));
        }, 3), ($container->services['Psr\\Log\\LoggerInterface'] ?? self::getLoggerInterfaceService($container)), ($container->services['PrestaShopBundle\\Cache\\LegacyCacheClearer'] ??= new \PrestaShopBundle\Cache\LegacyCacheClearer((\dirname(__DIR__, 5).'/var/cache/prod'.\DIRECTORY_SEPARATOR.''))));
    }
}
