<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTopContributorsControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\DistributionApiClient\Controller\Admin\TopContributorsController' shared autowired service.
     *
     * @return \PrestaShop\Module\DistributionApiClient\Controller\Admin\TopContributorsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShop\\Module\\DistributionApiClient\\Controller\\Admin\\TopContributorsController'] = $instance = new \PrestaShop\Module\DistributionApiClient\Controller\Admin\TopContributorsController();

        $instance->setContainer(($container->privates['.service_locator..KsBpQP'] ?? $container->load('get_ServiceLocator__KsBpQPService'))->withContext('PrestaShop\\Module\\DistributionApiClient\\Controller\\Admin\\TopContributorsController', $container));

        return $instance;
    }
}
