<?php

namespace Container4l75Fxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagFactoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Core\Grid\Factory\TagFactory' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\GridFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Factory\\TagFactory'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Definition\\Factory\\TagGridDefinitionFactory'] ?? $container->load('getTagGridDefinitionFactoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Data\\Factory\\TagGridDataFactory'] ?? $container->load('getTagGridDataFactoryService')), ($container->services['.container.private.prestashop.core.grid.filter.form_factory'] ?? $container->load('get_Container_Private_Prestashop_Core_Grid_Filter_FormFactoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)));
    }
}
