<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDKS1TLV\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDKS1TLV/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDKS1TLV.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerDKS1TLV\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerDKS1TLV\AdminKernelProdContainer([
    'container.build_hash' => 'DKS1TLV',
    'container.build_id' => '5e1c02c8',
    'container.build_time' => 1784421395,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDKS1TLV');
