<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0JjkXM5Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.0JjkXM5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0JjkXM5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'countryGridFactory' => ['services', 'prestashop.core.grid.factory.country', 'getPrestashop_Core_Grid_Factory_CountryService', true],
            'filters' => ['privates', '.errored..service_locator.0JjkXM5.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CountryFilters', NULL, 'Cannot autowire service ".service_locator.0JjkXM5": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CountryFilters" but no such service exists.'],
        ], [
            'countryGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CountryFilters',
        ]);
    }
}
