<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CKfKnt9Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.cKfKnt9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'definitionFactory' => ['services', 'prestashop.core.grid.definition.factory.outstanding', 'getPrestashop_Core_Grid_Definition_Factory_OutstandingService', true],
            'responseBuilder' => ['services', '.container.private.prestashop.bundle.grid.response_builder', 'get_Container_Private_Prestashop_Bundle_Grid_ResponseBuilderService', true],
        ], [
            'definitionFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\Definition\\Factory\\GridDefinitionFactoryInterface',
            'responseBuilder' => '?',
        ]);

        if (isset($container->privates['.service_locator.cKfKnt9'])) {
            return $container->privates['.service_locator.cKfKnt9'];
        }

        return $container->privates['.service_locator.cKfKnt9'] = $instance;
    }
}
