<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XZ6CKnAService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.XZ6CKnA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attributeFormHandler' => ['services', 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\AttributeGroupFormHandler', 'getAttributeGroupFormHandlerService', true],
            'attributeGroupFormBuilder' => ['services', 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\AttributeGroupFormBuilder', 'getAttributeGroupFormBuilderService', true],
        ], [
            'attributeFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
            'attributeGroupFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
        ]);

        if (isset($container->privates['.service_locator.XZ6CKnA'])) {
            return $container->privates['.service_locator.XZ6CKnA'];
        }

        return $container->privates['.service_locator.XZ6CKnA'] = $instance;
    }
}
