<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8QAI3fwService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.8QAI3fw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8QAI3fw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'iniConfiguration' => ['services', 'PrestaShop\\PrestaShop\\Core\\Configuration\\IniConfiguration', 'getIniConfigurationService', true],
            'kpiRowFactory' => ['services', 'prestashop.core.kpi_row.factory.cart', 'getPrestashop_Core_KpiRow_Factory_CartService', true],
        ], [
            'iniConfiguration' => 'PrestaShop\\PrestaShop\\Core\\Configuration\\IniConfiguration',
            'kpiRowFactory' => 'PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\HookableKpiRowFactory',
        ]);
    }
}
