<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGsG7ewService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.tGsG7ew' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tGsG7ew'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.tGsG7ew.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\SearchEngineFilters', NULL, 'Cannot autowire service ".service_locator.tGsG7ew": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\SearchEngineFilters" but no such service exists.'],
            'searchEngineGridFactory' => ['services', 'prestashop.core.grid.factory.search_engines', 'getPrestashop_Core_Grid_Factory_SearchEnginesService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\SearchEngineFilters',
            'searchEngineGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
