<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WMycj7ZService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.wMycj7Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.wMycj7Z.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TaxFilters', NULL, 'Cannot autowire service ".service_locator.wMycj7Z": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TaxFilters" but no such service exists.'],
            'taxGridFactory' => ['services', 'prestashop.core.grid.factory.tax', 'getPrestashop_Core_Grid_Factory_TaxService', true],
            'taxOptionsFormHandler' => ['services', 'prestashop.admin.tax_options.form_handler', 'getPrestashop_Admin_TaxOptions_FormHandlerService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TaxFilters',
            'taxGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'taxOptionsFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.wMycj7Z'])) {
            return $container->privates['.service_locator.wMycj7Z'];
        }

        return $container->privates['.service_locator.wMycj7Z'] = $instance;
    }
}
