<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gfkwu6fService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.gfkwu6f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formHandler' => ['privates', 'prestashop.module.link_block.form_handler', 'getPrestashop_Module_LinkBlock_FormHandlerService', true],
            'linkBlockFormDataProvider' => ['privates', 'PrestaShop\\Module\\LinkList\\Form\\LinkBlockFormDataProvider', 'getLinkBlockFormDataProviderService', true],
        ], [
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'linkBlockFormDataProvider' => 'PrestaShop\\Module\\LinkList\\Form\\LinkBlockFormDataProvider',
        ]);

        if (isset($container->privates['.service_locator.gfkwu6f'])) {
            return $container->privates['.service_locator.gfkwu6f'];
        }

        return $container->privates['.service_locator.gfkwu6f'] = $instance;
    }
}
