<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M_E4F5WService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.m.e4F5W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m.e4F5W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'choiceProvider' => ['services', 'prestashop.adapter.form.choice_provider.order_invoice_by_id', 'getPrestashop_Adapter_Form_ChoiceProvider_OrderInvoiceByIdService', true],
        ], [
            'choiceProvider' => 'PrestaShop\\PrestaShop\\Core\\Form\\ConfigurableFormChoiceProviderInterface',
        ]);
    }
}
