<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D5670jOService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.d5670jO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'generalFormHandler' => ['services', 'prestashop.adapter.administration.general.form_handler', 'getPrestashop_Adapter_Administration_General_FormHandlerService', true],
            'notificationsFormHandler' => ['services', 'prestashop.adapter.administration.notifications.form_handler', 'getPrestashop_Adapter_Administration_Notifications_FormHandlerService', true],
            'uploadQuotaFormHandler' => ['services', 'prestashop.adapter.administration.upload_quota.form_handler', 'getPrestashop_Adapter_Administration_UploadQuota_FormHandlerService', true],
        ], [
            'generalFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'notificationsFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'uploadQuotaFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.d5670jO'])) {
            return $container->privates['.service_locator.d5670jO'];
        }

        return $container->privates['.service_locator.d5670jO'] = $instance;
    }
}
