<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BTWYyfYService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.BTWYyfY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formHandler' => ['services', 'prestashop.adapter.order.delivery.slip.pdf.form_handler', 'getPrestashop_Adapter_Order_Delivery_Slip_Pdf_FormHandlerService', true],
            'legacyContext' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext', 'getLegacyContextService', false],
        ], [
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'legacyContext' => 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext',
        ]);

        if (isset($container->privates['.service_locator.BTWYyfY'])) {
            return $container->privates['.service_locator.BTWYyfY'];
        }

        return $container->privates['.service_locator.BTWYyfY'] = $instance;
    }
}
