<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ww94lt3Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ww94lt3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'databaseFormHandler' => ['services', 'prestashop.adapter.logs_database.form_handler', 'getPrestashop_Adapter_LogsDatabase_FormHandlerService', true],
            'filters' => ['privates', '.errored..service_locator.Ww94lt3.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\LogsFilters', NULL, 'Cannot autowire service ".service_locator.Ww94lt3": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\LogsFilters" but no such service exists.'],
            'formHandler' => ['services', 'prestashop.adapter.logs.form_handler', 'getPrestashop_Adapter_Logs_FormHandlerService', true],
            'gridLogFactory' => ['services', 'prestashop.core.grid.log_factory', 'getPrestashop_Core_Grid_LogFactoryService', true],
        ], [
            'databaseFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\LogsFilters',
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'gridLogFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);

        if (isset($container->privates['.service_locator.Ww94lt3'])) {
            return $container->privates['.service_locator.Ww94lt3'];
        }

        return $container->privates['.service_locator.Ww94lt3'] = $instance;
    }
}
