<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_7x20lZzService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.7x20lZz' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.7x20lZz'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Attribute\QueryHandler\GetAttributeForEditingHandler(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Attribute\\Repository\\AttributeRepository'] ?? $container->load('getAttributeRepositoryService')), ($container->services['prestashop.core.image.parser.image_tag_source_parser'] ??= new \PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser())))->handle(...), ['method' => 'handle']);
    }
}
