<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VmV6XtRService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.VmV6XtR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.cancel_product_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_CancelProductFormBuilderService', true],
            'formHandler' => ['services', 'prestashop.core.form.identifiable_object.cancellation_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_CancellationFormHandlerService', true],
        ], [
            'formBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.VmV6XtR'])) {
            return $container->privates['.service_locator.VmV6XtR'];
        }

        return $container->privates['.service_locator.VmV6XtR'] = $instance;
    }
}
