<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FPOUBxfService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.fPOUBxf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fPOUBxf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryDataProvider' => ['services', 'prestashop.adapter.data_provider.category', 'getPrestashop_Adapter_DataProvider_CategoryService', true],
        ], [
            'categoryDataProvider' => 'PrestaShop\\PrestaShop\\Adapter\\Category\\CategoryDataProvider',
        ]);
    }
}
