<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_SgJgM7JService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.sgJgM7J' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.sgJgM7J'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Attribute\CommandHandler\DeleteAttributeTextureImageHandler(($container->privates['PrestaShop\\PrestaShop\\Adapter\\File\\Uploader\\AttributeFileUploader'] ??= new \PrestaShop\PrestaShop\Adapter\File\Uploader\AttributeFileUploader())))->handle(...), ['method' => 'handle']);
    }
}
