<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RkU2aBBService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.rkU2aBB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'context' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext', 'getLegacyContextService', false],
            'orderStateFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.order_state_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_OrderStateFormBuilderService', true],
            'orderStateFormHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.order_state_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_OrderStateFormHandlerService', true],
        ], [
            'context' => 'PrestaShop\\PrestaShop\\Adapter\\LegacyContext',
            'orderStateFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'orderStateFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.rkU2aBB'])) {
            return $container->privates['.service_locator.rkU2aBB'];
        }

        return $container->privates['.service_locator.rkU2aBB'] = $instance;
    }
}
