<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZNpF1fLService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.zNpF1fL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriesGridFactory' => ['services', 'prestashop.core.grid.factory.category', 'getPrestashop_Core_Grid_Factory_CategoryService', true],
            'filters' => ['privates', '.errored..service_locator.zNpF1fL.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CategoryFilters', NULL, 'Cannot autowire service ".service_locator.zNpF1fL": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CategoryFilters" but no such service exists.'],
        ], [
            'categoriesGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CategoryFilters',
        ]);

        if (isset($container->privates['.service_locator.zNpF1fL'])) {
            return $container->privates['.service_locator.zNpF1fL'];
        }

        return $container->privates['.service_locator.zNpF1fL'] = $instance;
    }
}
