<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AM62hHIService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.AM62hHI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartGridFactory' => ['services', 'prestashop.core.grid.factory.cart', 'getPrestashop_Core_Grid_Factory_CartService', true],
            'cartsKpiFactory' => ['services', 'prestashop.core.kpi_row.factory.carts', 'getPrestashop_Core_KpiRow_Factory_CartsService', true],
            'filters' => ['privates', '.errored..service_locator.AM62hHI.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CartFilter', NULL, 'Cannot autowire service ".service_locator.AM62hHI": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CartFilter" but no such service exists.'],
        ], [
            'cartGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactory',
            'cartsKpiFactory' => 'PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\HookableKpiRowFactory',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CartFilter',
        ]);

        if (isset($container->privates['.service_locator.AM62hHI'])) {
            return $container->privates['.service_locator.AM62hHI'];
        }

        return $container->privates['.service_locator.AM62hHI'] = $instance;
    }
}
