<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RvwkuDoService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.rvwkuDo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'maintenanceFormHandler' => ['services', 'prestashop.adapter.maintenance.form_handler', 'getPrestashop_Adapter_Maintenance_FormHandlerService', true],
        ], [
            'maintenanceFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.rvwkuDo'])) {
            return $container->privates['.service_locator.rvwkuDo'];
        }

        return $container->privates['.service_locator.rvwkuDo'] = $instance;
    }
}
