<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__VTJhpLService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator..VTJhpL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attachmentFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.attachment_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_AttachmentFormBuilderService', true],
            'attachmentFormHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.attachment_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_AttachmentFormHandlerService', true],
        ], [
            'attachmentFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'attachmentFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator..VTJhpL'])) {
            return $container->privates['.service_locator..VTJhpL'];
        }

        return $container->privates['.service_locator..VTJhpL'] = $instance;
    }
}
