<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_X7vX8aSService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.x7vX8aS' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.x7vX8aS'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Shipment\QueryHandler\GetShipmentForEditingHandler(($container->services['PrestaShopBundle\\Entity\\Repository\\ShipmentRepository'] ?? $container->load('getShipmentRepositoryService')), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container))))->handle(...), ['method' => 'handle']);
    }
}
