<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TosaEEService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.Tosa_EE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tosa_EE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'addressGridFactory' => ['services', 'prestashop.core.grid.grid_factory.address', 'getPrestashop_Core_Grid_GridFactory_AddressService', true],
            'filters' => ['privates', '.errored..service_locator.Tosa_EE.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AddressFilters', NULL, 'Cannot autowire service ".service_locator.Tosa_EE": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AddressFilters" but no such service exists.'],
        ], [
            'addressGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AddressFilters',
        ]);
    }
}
