<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NGP2ybService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.NG_P2yb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NG_P2yb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attributeGroupGridFactory' => ['services', 'prestashop.core.grid.factory.attribute_group', 'getPrestashop_Core_Grid_Factory_AttributeGroupService', true],
            'filters' => ['privates', '.errored..service_locator.NG_P2yb.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeGroupFilters', NULL, 'Cannot autowire service ".service_locator.NG_P2yb": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeGroupFilters" but no such service exists.'],
        ], [
            'attributeGroupGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeGroupFilters',
        ]);
    }
}
