<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_JnooMeCService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.JnooMeC' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountTypeRepository'] ?? $container->load('getDiscountTypeRepositoryService'));

        return $container->privates['.messenger.handler_descriptor.JnooMeC'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\AddDiscountHandler(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'] ?? $container->load('getDiscountRepositoryService')), new \PrestaShop\PrestaShop\Adapter\Discount\Update\DiscountBuilder($a), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Validate\\DiscountValidator'] ?? $container->load('getDiscountValidatorService')), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Update\\DiscountConditionsUpdater'] ?? $container->load('getDiscountConditionsUpdaterService')), $a))->handle(...), ['method' => 'handle']);
    }
}
