<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TZb3aj6Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.TZb3aj6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'searchEngineFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.search_engine_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_SearchEngineFormBuilderService', true],
            'searchEngineFormHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.search_engine_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_SearchEngineFormHandlerService', true],
        ], [
            'searchEngineFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'searchEngineFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.TZb3aj6'])) {
            return $container->privates['.service_locator.TZb3aj6'];
        }

        return $container->privates['.service_locator.TZb3aj6'] = $instance;
    }
}
