<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CU2XService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.cU_2X__' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cU_2X__'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'moduleAdapter' => ['services', 'prestashop.adapter.legacy.module', 'getPrestashop_Adapter_Legacy_ModuleService', true],
            'shopContext' => ['services', 'PrestaShop\\PrestaShop\\Core\\Multistore\\MultistoreContextCheckerInterface', 'getMultistoreContextCheckerInterfaceService', true],
            'validateAdapter' => ['services', 'prestashop.adapter.validate', 'getPrestashop_Adapter_ValidateService', true],
        ], [
            'moduleAdapter' => 'PrestaShop\\PrestaShop\\Adapter\\Module\\Module',
            'shopContext' => '?',
            'validateAdapter' => 'PrestaShop\\PrestaShop\\Adapter\\Validate',
        ]);
    }
}
