<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GcUBKKIService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.GcUBKKI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GcUBKKI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'uploadQuotaFormHandler' => ['services', 'prestashop.adapter.administration.upload_quota.form_handler', 'getPrestashop_Adapter_Administration_UploadQuota_FormHandlerService', true],
        ], [
            'uploadQuotaFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
