<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__HzSJBVService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator..hzSJBV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..hzSJBV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'geolocationByIpAddressFormHandler' => ['services', 'prestashop.admin.geolocation.by_ip_address.form_handler', 'getPrestashop_Admin_Geolocation_ByIpAddress_FormHandlerService', true],
        ], [
            'geolocationByIpAddressFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
