<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q9_34gRService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.q9.34gR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'listFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.combination_list_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_CombinationListFormBuilderService', true],
            'listFormHandler' => ['services', 'prestashop.core.form.identifiable_object.combination_list_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_CombinationListFormHandlerService', true],
        ], [
            'listFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'listFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator.q9.34gR'])) {
            return $container->privates['.service_locator.q9.34gR'];
        }

        return $container->privates['.service_locator.q9.34gR'] = $instance;
    }
}
