<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_53U4pIService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.53U4pI_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formHandler' => ['services', 'prestashop.admin.translations_settings.copy_language.form_handler', 'getPrestashop_Admin_TranslationsSettings_CopyLanguage_FormHandlerService', true],
            'languageCopier' => ['services', 'prestashop.adapter.language.copier', 'getPrestashop_Adapter_Language_CopierService', true],
        ], [
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
            'languageCopier' => 'PrestaShop\\PrestaShop\\Core\\Language\\Copier\\LanguageCopierInterface',
        ]);

        if (isset($container->privates['.service_locator.53U4pI_'])) {
            return $container->privates['.service_locator.53U4pI_'];
        }

        return $container->privates['.service_locator.53U4pI_'] = $instance;
    }
}
