<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DWc2Ud_Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.dWc2Ud.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dWc2Ud.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryTreeFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.category_tree_selector_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_CategoryTreeSelectorFormBuilderService', true],
            'editProductFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.edit_product_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_EditProductFormBuilderService', true],
            'productFormHandler' => ['services', 'prestashop.core.form.identifiable_object.product_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_ProductFormHandlerService', true],
        ], [
            'categoryTreeFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'editProductFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'productFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);
    }
}
