<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9JEoFZ_Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9JEoFZ.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9JEoFZ.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.9JEoFZ..PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StateFilters', NULL, 'Cannot autowire service ".service_locator.9JEoFZ.": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StateFilters" but no such service exists.'],
            'gridFactory' => ['services', 'prestashop.core.grid.grid_factory.state', 'getPrestashop_Core_Grid_GridFactory_StateService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StateFilters',
            'gridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
