<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6KSh6CjService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.6KSh6Cj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'prestashop.router', 'getPrestashop_RouterService', true],
        ], [
            'router' => '?',
        ]);

        if (isset($container->privates['.service_locator.6KSh6Cj'])) {
            return $container->privates['.service_locator.6KSh6Cj'];
        }

        return $container->privates['.service_locator.6KSh6Cj'] = $instance;
    }
}
