<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SLYVpjNService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.SLYVpjN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SLYVpjN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'previewUrlProvider' => ['services', 'prestashop.adapter.shop.url.cms_provider', 'getPrestashop_Adapter_Shop_Url_CmsProviderService', true],
        ], [
            'previewUrlProvider' => 'PrestaShop\\PrestaShop\\Adapter\\Shop\\Url\\CmsProvider',
        ]);
    }
}
