<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R_KZezMService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.r.kZezM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r.kZezM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.r.kZezM.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OutstandingFilters', NULL, 'Cannot autowire service ".service_locator.r.kZezM": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OutstandingFilters" but no such service exists.'],
            'gridFactory' => ['services', 'prestashop.core.grid.factory.outstanding', 'getPrestashop_Core_Grid_Factory_OutstandingService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OutstandingFilters',
            'gridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
