<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XBDWhService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.XBD__Wh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XBD__Wh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statesProvider' => ['services', 'prestashop.adapter.form.choice_provider.country_state_by_id', 'getPrestashop_Adapter_Form_ChoiceProvider_CountryStateByIdService', true],
        ], [
            'statesProvider' => 'PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\CountryStateByIdChoiceProvider',
        ]);
    }
}
