<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T6_DJ74Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.t6.DJ74' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t6.DJ74'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.t6.DJ74.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TagFilters', NULL, 'Cannot autowire service ".service_locator.t6.DJ74": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TagFilters" but no such service exists.'],
            'tagGridFactory' => ['services', 'PrestaShop\\PrestaShop\\Core\\Grid\\Factory\\TagFactory', 'getTagFactoryService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TagFilters',
            'tagGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
