<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_3X7HYRTService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.3X7HYRT' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.3X7HYRT'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Shipment\QueryHandler\ListAvailableShipmentsHandler(($container->services['PrestaShopBundle\\Entity\\Repository\\ShipmentRepository'] ?? $container->load('getShipmentRepositoryService')), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container))))->handle(...), ['method' => 'handle']);
    }
}
