<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_MmWuojJService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.mmWuojJ' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.mmWuojJ'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.webservice.command_handler.bulk_delete_webservice_key_handler'] ?? $container->load('getPrestashop_Adapter_Webservice_CommandHandler_BulkDeleteWebserviceKeyHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
