<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__YsK2GService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator..Ys_k2G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taxFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.tax_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_TaxFormBuilderService', true],
            'taxFormHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.tax_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_TaxFormHandlerService', true],
        ], [
            'taxFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'taxFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);

        if (isset($container->privates['.service_locator..Ys_k2G'])) {
            return $container->privates['.service_locator..Ys_k2G'];
        }

        return $container->privates['.service_locator..Ys_k2G'] = $instance;
    }
}
