<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailableCarriersForShipmentChoiceProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\AvailableCarriersForShipmentChoiceProvider' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\AvailableCarriersForShipmentChoiceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'));

        if (isset($container->privates['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\AvailableCarriersForShipmentChoiceProvider'])) {
            return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\AvailableCarriersForShipmentChoiceProvider'];
        }

        $instance = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\AvailableCarriersForShipmentChoiceProvider($a, ($container->services['PrestaShopBundle\\Entity\\Repository\\ShipmentRepository'] ?? $container->load('getShipmentRepositoryService')), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)));

        if (isset($container->privates['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\AvailableCarriersForShipmentChoiceProvider'])) {
            return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\AvailableCarriersForShipmentChoiceProvider'];
        }

        return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\AvailableCarriersForShipmentChoiceProvider'] = $instance;
    }
}
