<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBillingContextWrapperService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper' shared service.
     *
     * @return \PrestaShopCorp\Billing\Wrappers\BillingContextWrapper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopCorp\\Billing\\Wrappers\\BillingContextWrapper'] = new \PrestaShopCorp\Billing\Wrappers\BillingContextWrapper(($container->services['PrestaShop\\PsAccountsInstaller\\Installer\\Facade\\PsAccounts'] ?? $container->load('getPsAccountsService')), ($container->services['ps_facebook.context'] ?? $container->load('getPsFacebook_ContextService')), ($container->services['ps_facebook.billing_env'] ?? $container->load('getPsFacebook_BillingEnvService')));
    }
}
