<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrierServiceService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\Psshipping\Domain\Carriers\CarrierService' shared service.
     *
     * @return \PrestaShop\Module\Psshipping\Domain\Carriers\CarrierService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\CarrierService'] = new \PrestaShop\Module\Psshipping\Domain\Carriers\CarrierService(($container->services['psshipping'] ?? $container->load('getPsshippingService')), ($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\CarrierRepository'] ?? $container->load('getCarrierRepositoryService')));
    }
}
