<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandMappingAdapterService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\ApiPlatform\OpenApi\Adapter\CommandMappingAdapter' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\OpenApi\Adapter\CommandMappingAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\ApiPlatform\\OpenApi\\Adapter\\CommandMappingAdapter'] = new \PrestaShopBundle\ApiPlatform\OpenApi\Adapter\CommandMappingAdapter(($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)));
    }
}
