<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCombinationImagesChoiceTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Product\Combination\CombinationImagesChoiceType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Product\Combination\CombinationImagesChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['.container.private.prestashop.core.form.choice_provider.product_images_choice_provider'] ?? $container->load('get_Container_Private_Prestashop_Core_Form_ChoiceProvider_ProductImagesChoiceProviderService'));

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Combination\\CombinationImagesChoiceType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Combination\\CombinationImagesChoiceType'];
        }

        $instance = new \PrestaShopBundle\Form\Admin\Sell\Product\Combination\CombinationImagesChoiceType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(false), $a);

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Combination\\CombinationImagesChoiceType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Combination\\CombinationImagesChoiceType'];
        }

        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Combination\\CombinationImagesChoiceType'] = $instance;
    }
}
