<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryFilters2Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.zNpF1fL.PrestaShop\PrestaShop\Core\Search\Filters\CategoryFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\CategoryFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zNpF1fL": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CategoryFilters" but no such service exists.');
    }
}
