<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerFilters2Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.eI5Ptae.PrestaShop\PrestaShop\Core\Search\Filters\CustomerFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\CustomerFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eI5Ptae": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerFilters" but no such service exists.');
    }
}
