<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountFeaturesTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Discount\DiscountFeaturesType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Discount\DiscountFeaturesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Discount\\DiscountFeaturesType'] = new \PrestaShopBundle\Form\Admin\Sell\Discount\DiscountFeaturesType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['.container.private.prestashop.adapter.form.choice_provider.features_choice_provider'] ?? $container->load('get_Container_Private_Prestashop_Adapter_Form_ChoiceProvider_FeaturesChoiceProviderService')));
    }
}
