<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeletePaymentTokenActionService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\PaymentToken\Action\DeletePaymentTokenAction' shared service.
     *
     * @return \PsCheckout\Core\PaymentToken\Action\DeletePaymentTokenAction
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\PaymentToken\\Action\\DeletePaymentTokenAction'] = new \PsCheckout\Core\PaymentToken\Action\DeletePaymentTokenAction(($container->services['PsCheckout\\Infrastructure\\Repository\\PaymentTokenRepository'] ?? $container->load('getPaymentTokenRepositoryService')), ($container->services['PsCheckout\\Api\\Http\\CheckoutHttpClient'] ?? $container->load('getCheckoutHttpClientService')), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)));
    }
}
