<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportModuleTranslationsCommandService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Command\ExportModuleTranslationsCommand' shared service.
     *
     * @return \PrestaShopBundle\Command\ExportModuleTranslationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Command\\ExportModuleTranslationsCommand'] = $instance = new \PrestaShopBundle\Command\ExportModuleTranslationsCommand(($container->services['prestashop.translation.export.translation_catalogue'] ?? $container->load('getPrestashop_Translation_Export_TranslationCatalogueService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), (\dirname(__DIR__, 5).'/modules/'));

        $instance->setName('prestashop:translation:export-module');
        $instance->setDescription('Export module translations to XLF files');

        return $instance;
    }
}
