<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeatureFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ZTOaeMR.PrestaShop\PrestaShop\Core\Search\Filters\FeatureFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\FeatureFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZTOaeMR": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\FeatureFilters" but no such service exists.');
    }
}
