<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookDisplayOrderConfirmationService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\Psshipping\Hooks\HookDisplayOrderConfirmation' shared service.
     *
     * @return \PrestaShop\Module\Psshipping\Hooks\HookDisplayOrderConfirmation
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Psshipping\\Hooks\\HookDisplayOrderConfirmation'] = new \PrestaShop\Module\Psshipping\Hooks\HookDisplayOrderConfirmation(($container->services['psshipping'] ?? $container->load('getPsshippingService')), ($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\CarrierRepository'] ?? $container->load('getCarrierRepositoryService')), ($container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\PickupPoints\\PsshippingAddressOrdersRepository'] ?? $container->load('getPsshippingAddressOrdersRepositoryService')), ($container->services['psshipping.context'] ?? $container->load('getPsshipping_ContextService')));
    }
}
