<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstaller4Service extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Infrastructure\Bootstrap\Install\Installer' shared service.
     *
     * @return \PsCheckout\Infrastructure\Bootstrap\Install\Installer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\Installer'] = new \PsCheckout\Infrastructure\Bootstrap\Install\Installer(($container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\ConfigurationInstaller'] ?? $container->load('getConfigurationInstallerService')), ($container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\DatabaseTableInstaller'] ?? $container->load('getDatabaseTableInstallerService')), ($container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\FundingSourceInstaller'] ?? $container->load('getFundingSourceInstallerService')), ($container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\OrderStateInstaller'] ?? $container->load('getOrderStateInstallerService')), ($container->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\CompatibilityRulesInstaller'] ?? $container->load('getCompatibilityRulesInstallerService')));
    }
}
