<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogsFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Ww94lt3.PrestaShop\PrestaShop\Core\Search\Filters\LogsFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\LogsFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ww94lt3": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\LogsFilters" but no such service exists.');
    }
}
