<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.4YFbf7z.PrestaShop\PrestaShop\Core\Search\Filters\LanguageFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\LanguageFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4YFbf7z": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\LanguageFilters" but no such service exists.');
    }
}
