<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaaslandOrderHttpClientService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Api\Http\MaaslandOrderHttpClient' shared service.
     *
     * @return \PsCheckout\Api\Http\MaaslandOrderHttpClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Api\\Http\\MaaslandOrderHttpClient'] = new \PsCheckout\Api\Http\MaaslandOrderHttpClient(($container->services['PsCheckout\\Api\\Http\\Configuration\\MaaslandOrderHttpClientConfigurationBuilder'] ?? $container->load('getMaaslandOrderHttpClientConfigurationBuilderService')));
    }
}
