<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMbeStandardCarrierConfigurationService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\Psshipping\Domain\Carriers\MbeStandardCarrierConfiguration' shared service.
     *
     * @return \PrestaShop\Module\Psshipping\Domain\Carriers\MbeStandardCarrierConfiguration
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Psshipping\\Domain\\Carriers\\MbeStandardCarrierConfiguration'] = new \PrestaShop\Module\Psshipping\Domain\Carriers\MbeStandardCarrierConfiguration('prestashop.core.command_bus');
    }
}
