<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotCustomizableProductValidatorService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Core\ConstraintValidator\NotCustomizableProductValidator' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\ConstraintValidator\NotCustomizableProductValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\ConstraintValidator\\NotCustomizableProductValidator'] = new \PrestaShop\PrestaShop\Core\ConstraintValidator\NotCustomizableProductValidator(($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepository3Service')));
    }
}
