<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdersRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\Psshipping\Domain\Orders\OrdersRepository' shared service.
     *
     * @return \PrestaShop\Module\Psshipping\Domain\Orders\OrdersRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Psshipping\\Domain\\Orders\\OrdersRepository'] = new \PrestaShop\Module\Psshipping\Domain\Orders\OrdersRepository(($container->services['psshipping'] ?? $container->load('getPsshippingService')));
    }
}
