<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderShipmentCreatorService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Shipment\OrderShipmentCreator' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Shipment\OrderShipmentCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Shipment\\OrderShipmentCreator'] = new \PrestaShop\PrestaShop\Adapter\Shipment\OrderShipmentCreator(($container->services['PrestaShopBundle\\Entity\\Repository\\ShipmentRepository'] ?? $container->load('getShipmentRepositoryService')));
    }
}
