<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_Improve_Design_ImageSettings_FormDataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.improve.design.image_settings.form_data_provider' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\Design\ImageSettings\ImageSettingsFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'));

        if (isset($container->services['prestashop.admin.improve.design.image_settings.form_data_provider'])) {
            return $container->services['prestashop.admin.improve.design.image_settings.form_data_provider'];
        }

        $instance = new \PrestaShopBundle\Form\Admin\Improve\Design\ImageSettings\ImageSettingsFormDataProvider(($container->services['prestashop.core.query_bus'] ?? $container->load('getPrestashop_Core_QueryBusService')), $a);

        if (isset($container->services['prestashop.admin.improve.design.image_settings.form_data_provider'])) {
            return $container->services['prestashop.admin.improve.design.image_settings.form_data_provider'];
        }

        return $container->services['prestashop.admin.improve.design.image_settings.form_data_provider'] = $instance;
    }
}
