<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Discount_PriorityService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.discount.priority' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Domain\Discount\ValueObject\DiscountPriority
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.discount.priority'] = new \PrestaShop\PrestaShop\Core\Domain\Discount\ValueObject\DiscountPriority();
    }
}
