<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentHttpClientConfigurationBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Api\Http\Configuration\PaymentHttpClientConfigurationBuilder' shared service.
     *
     * @return \PsCheckout\Api\Http\Configuration\PaymentHttpClientConfigurationBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Api\\Http\\Configuration\\PaymentHttpClientConfigurationBuilder'] = new \PsCheckout\Api\Http\Configuration\PaymentHttpClientConfigurationBuilder(($container->services['PsCheckout\\Infrastructure\\Environment\\Env'] ?? $container->load('getEnv4Service')), ($container->services['PsCheckout\\Infrastructure\\Repository\\PsAccountRepository'] ?? $container->load('getPsAccountRepositoryService')), ($container->services['Psr\\Log\\LoggerInterface'] ?? self::getLoggerInterfaceService($container)), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Link'] ?? $container->load('getLinkService')), ($container->services['ps_checkout.module'] ?? $container->load('getPsCheckout_ModuleService'))->version);
    }
}
