<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Email_LegacyTemplateListerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.email.legacy_template_lister' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Email\LegacyEmailTemplateLister
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.email.legacy_template_lister'] = new \PrestaShop\PrestaShop\Core\Email\LegacyEmailTemplateLister((\dirname(__DIR__, 5).'/mails'), (\dirname(__DIR__, 5).'/modules'));
    }
}
