<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentHttpClientService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Api\Http\PaymentHttpClient' shared service.
     *
     * @return \PsCheckout\Api\Http\PaymentHttpClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Api\\Http\\PaymentHttpClient'] = new \PsCheckout\Api\Http\PaymentHttpClient(($container->services['PsCheckout\\Api\\Http\\Configuration\\PaymentHttpClientConfigurationBuilder'] ?? $container->load('getPaymentHttpClientConfigurationBuilderService')));
    }
}
