<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaypalModuleService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Presentation\Presenter\Settings\Admin\Modules\PaypalModule' shared service.
     *
     * @return \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\PaypalModule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\PaypalModule'] = new \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\PaypalModule(($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)));
    }
}
