<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaveBatchConfigurationActionInterfaceService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Infrastructure\Action\SaveBatchConfigurationActionInterface' shared service.
     *
     * @return \PsCheckout\Infrastructure\Action\SaveBatchConfigurationAction
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Infrastructure\\Action\\SaveBatchConfigurationActionInterface'] = new \PsCheckout\Infrastructure\Action\SaveBatchConfigurationAction(($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)));
    }
}
