<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplementaryDataNodeBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\Order\Builder\Node\SupplementaryDataNodeBuilder' shared service.
     *
     * @return \PsCheckout\Core\Order\Builder\Node\SupplementaryDataNodeBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\Order\\Builder\\Node\\SupplementaryDataNodeBuilder'] = new \PsCheckout\Core\Order\Builder\Node\SupplementaryDataNodeBuilder(($container->services['PsCheckout\\Infrastructure\\Repository\\CountryRepository'] ?? $container->load('getCountryRepository3Service')), ($container->services['PsCheckout\\Infrastructure\\Repository\\StateRepository'] ??= new \PsCheckout\Infrastructure\Repository\StateRepository()));
    }
}
