<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetReversedOrderStateActionService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\OrderState\Action\SetReversedOrderStateAction' shared service.
     *
     * @return \PsCheckout\Core\OrderState\Action\SetReversedOrderStateAction
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\OrderState\\Action\\SetReversedOrderStateAction'] = new \PsCheckout\Core\OrderState\Action\SetReversedOrderStateAction(($container->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRepository'] ?? $container->load('getPayPalOrderRepositoryService')), ($container->services['PsCheckout\\Infrastructure\\Repository\\OrderRepository'] ??= new \PsCheckout\Infrastructure\Repository\OrderRepository()), ($container->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] ?? self::getConfiguration2Service($container)), ($container->services['PsCheckout\\Core\\OrderState\\Service\\OrderStateMapper'] ?? $container->load('getOrderStateMapperService')), ($container->services['PsCheckout\\Core\\OrderState\\Action\\ChangeOrderStateAction'] ?? $container->load('getChangeOrderStateActionService')));
    }
}
