<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipmentRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Entity\Repository\ShipmentRepository' shared service.
     *
     * @return \PrestaShopBundle\Entity\Repository\ShipmentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Entity\\Repository\\ShipmentRepository'] = $instance = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))->getRepository('PrestaShopBundle\\Entity\\Shipment');

        $instance->setTablePrefix('vovsk_');

        return $instance;
    }
}
