<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.t6.DJ74.PrestaShop\PrestaShop\Core\Search\Filters\TagFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\TagFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.t6.DJ74": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TagFilters" but no such service exists.');
    }
}
