<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackingDatabaseHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Core\PayPal\ShippingTracking\Service\TrackingDatabaseHandler' shared service.
     *
     * @return \PsCheckout\Core\PayPal\ShippingTracking\Service\TrackingDatabaseHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Service\\TrackingDatabaseHandler'] = new \PsCheckout\Core\PayPal\ShippingTracking\Service\TrackingDatabaseHandler(($container->services['PsCheckout\\Infrastructure\\Repository\\ShippingTrackingRepository'] ?? $container->load('getShippingTrackingRepositoryService')), ($container->services['Psr\\Log\\LoggerInterface'] ?? self::getLoggerInterfaceService($container)));
    }
}
