<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdatePositionProcessorService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\ApiPlatform\Processor\UpdatePositionProcessor' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\Processor\UpdatePositionProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\ApiPlatform\\Processor\\UpdatePositionProcessor'] = new \PrestaShopBundle\ApiPlatform\Processor\UpdatePositionProcessor($container, ($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionUpdateFactory'] ?? $container->load('getPositionUpdateFactoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Position\\GridPositionUpdater'] ?? $container->load('getGridPositionUpdaterService')), ($container->privates['PrestaShopBundle\\ApiPlatform\\Serializer\\CQRSApiSerializer'] ?? self::getCQRSApiSerializerService($container)));
    }
}
