<?php

namespace ContainerDKS1TLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookHttpClientService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PsCheckout\Api\Http\WebhookHttpClient' shared service.
     *
     * @return \PsCheckout\Api\Http\WebhookHttpClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PsCheckout\\Api\\Http\\WebhookHttpClient'] = new \PsCheckout\Api\Http\WebhookHttpClient(($container->services['PsCheckout\\Api\\Http\\Configuration\\WebhookHttpClientConfigurationBuilder'] ?? $container->load('getWebhookHttpClientConfigurationBuilderService')));
    }
}
