<?php

namespace Proxies\__CG__\PrestaShopBundle\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Shipment extends \PrestaShopBundle\Entity\Shipment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'id', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'orderId', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'carrierId', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'addressId', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'shippingCostTaxExcluded', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'shippingCostTaxIncluded', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'packedAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'shippedAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'deliveredAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'cancelledAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'trackingNumber', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'createdAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'updatedAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'products'];
        }

        return ['__isInitialized__', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'id', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'orderId', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'carrierId', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'addressId', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'shippingCostTaxExcluded', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'shippingCostTaxIncluded', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'packedAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'shippedAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'deliveredAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'cancelledAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'trackingNumber', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'createdAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'updatedAt', '' . "\0" . 'PrestaShopBundle\\Entity\\Shipment' . "\0" . 'products'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Shipment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', []);

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarrierId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarrierId', []);

        return parent::getCarrierId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressId', []);

        return parent::getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCostTaxExcluded(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCostTaxExcluded', []);

        return parent::getShippingCostTaxExcluded();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCostTaxIncluded(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCostTaxIncluded', []);

        return parent::getShippingCostTaxIncluded();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackedAt', []);

        return parent::getPackedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippedAt', []);

        return parent::getShippedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveredAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveredAt', []);

        return parent::getDeliveredAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelledAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelledAt', []);

        return parent::getCancelledAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingNumber', []);

        return parent::getTrackingNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', []);

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderId(int $orderId): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderId', [$orderId]);

        return parent::setOrderId($orderId);
    }

    /**
     * {@inheritDoc}
     */
    public function setCarrierId(int $carrierId): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarrierId', [$carrierId]);

        return parent::setCarrierId($carrierId);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressId(int $addressId): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressId', [$addressId]);

        return parent::setAddressId($addressId);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCostTaxExcluded(float $shippingCostTaxExcluded): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCostTaxExcluded', [$shippingCostTaxExcluded]);

        return parent::setShippingCostTaxExcluded($shippingCostTaxExcluded);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCostTaxIncluded(float $shippingCostTaxIncluded): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCostTaxIncluded', [$shippingCostTaxIncluded]);

        return parent::setShippingCostTaxIncluded($shippingCostTaxIncluded);
    }

    /**
     * {@inheritDoc}
     */
    public function setPackedAt(?\DateTime $packedAt): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackedAt', [$packedAt]);

        return parent::setPackedAt($packedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippedAt(?\DateTime $shippedAt): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippedAt', [$shippedAt]);

        return parent::setShippedAt($shippedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveredAt(?\DateTime $deliveredAt): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveredAt', [$deliveredAt]);

        return parent::setDeliveredAt($deliveredAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingNumber(?string $trackingNumber): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingNumber', [$trackingNumber]);

        return parent::setTrackingNumber($trackingNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelledAt(?\DateTime $cancelledAt): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelledAt', [$cancelledAt]);

        return parent::setCancelledAt($cancelledAt);
    }

    /**
     * {@inheritDoc}
     */
    public function addShipmentProduct(\PrestaShopBundle\Entity\ShipmentProduct $shipmentProduct): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShipmentProduct', [$shipmentProduct]);

        return parent::addShipmentProduct($shipmentProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\PrestaShopBundle\Entity\ShipmentProduct $product): \PrestaShopBundle\Entity\Shipment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', [$product]);

        return parent::removeProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function updatedTimestamps(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updatedTimestamps', []);

        parent::updatedTimestamps();
    }

}
